<?php
/**
 * 中间控制器
 * Author: xiaojie
 * DateTime: 2018/12/02 09:54
 */
namespace cmf\controller;

use think\Db;

class JieBaseController extends HomeBaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->visit_record();
	}

	/**
	 * 访客记录
	 */
	private function visit_record()
	{
		$visitModel = Db::name('visit');
		$user_ip = $this->request->ip();
		if($user_ip != '180.213.71.206' and $user_ip != '59.109.129.191'){
			$join_url = $this->request->baseUrl();
			$data = $this->getAddress($user_ip);
			if(cmf_is_mobile()){
				$join_type = 'mobile';
			}else{
				$join_type = 'pc';
			}

			$map['user_ip'] = $user_ip;
			$map['join_url'] = $join_url;
			$map['create_time'] = ['gt',time()-300];
			$res = $visitModel->where($map)->find();
			if(!$res){
				$visitModel->insert([
					'user_ip' => $user_ip,
					'create_time' => time(),
					'create_date' => date('Y-m-d H:i:s'),
					'address' => $data['result']['ad_info']['province'],
					'address_detail' => $data['result']['ad_info']['city'] . $data['result']['ad_info']['district'],
					'join_url' => $join_url,
					'join_type' => $join_type,
				]);
			}
		}
	}

	/**
	 * 腾讯根据ip获取当前位置信息
	 * @param $ip 当前ip地址
	 * @return bool
	 */
	private function getAddress($ip)
	{
		$key = 'HGLBZ-WD66X-2H74V-TJ6NI-NHNWZ-DNBJ5';
		$url = 'https://apis.map.qq.com/ws/location/v1/ip?ip=' . $ip . '&key=' .$key;
		$data = json_decode(file_get_contents($url),true);
		if($data['status'] !== 0){
			return false;
		}
		return $data;
	}

	/**
	 * 获取banner图
	 * @param $slide_id
	 * @return false|\PDOStatement|string|\think\Collection
	 */
	public function getSlide($slide_id)
	{
		$list = Db::name('slide_item')
			->field('title,image,url')
			->where('slide_id',$slide_id)
			->order('list_order')
			->limit(3)
			->select();
		return $list;
	}

    /**
     *  API返回信息格式函数 ；0失败，1成功
     * @param string $code
     * @param string $message
     * @param array $data
     */
    public function apiResponse($code = '', $msg = '', $data = array())
    {
        header('Access-Control-Allow-Origin: *');
        header('Content-Type:application/json; charset=utf-8');
        $result = array(
            'code' => $code,
            'msg' => $msg,
            'data' => $data,
        );
        die(json_encode($result, JSON_UNESCAPED_UNICODE));

    }

}